window.quizTopics = window.quizTopics || {};

window.quizTopics.topic2 = {
  id: 'topic2',
  label: 'Topic 2',
  title: 'Text Processing: grep & sed',
  description: 'Search, filter, and transform text streams using UNIX utilities',
  questions: {
    single: [
      { id: 'm1-t2-single-001', topic: 'History', text: 'From which historical editor command does the utility "grep" derive its name?', options: ['g/re/s', 'g/re/p', 'grep/all', 'g/regex/print'], answer: [1], fact: 'grep comes from the ed editor command g/re/p (globally search for a regular expression and print).' },
      { id: 'm1-t2-single-002', topic: 'grep Basics', text: 'When using grep -c "error" on a file, what exactly is being counted and reported?', options: ['The total number of times the word "error" appears', 'The number of lines that do not contain the word "error"', 'The total character count of all matching strings', 'The number of lines containing at least one match'], answer: [3], fact: 'grep -c counts the number of matching lines, not the total number of individual matches.' },
      { id: 'm1-t2-single-003', topic: 'grep Basics', text: 'Which grep flag is essential for ensuring a search for "admin" does not accidentally match the word "administrator"?', options: ['-v', '-x', '-w', '-q'], answer: [2], fact: 'The -w flag forces grep to match only whole words with boundaries on both sides.' },
      { id: 'm1-t2-single-004', topic: 'grep Intermediate', text: 'How does grep -q handle its output when a match is found?', options: ['It prints the matching line to a background file.', 'It prints only the matched fragment of the string.', 'It suppresses standard output and sets an exit status of 0.', 'It displays the line number without the text.'], answer: [2], fact: 'The -q (quiet) flag prints nothing and answers strictly through the exit status, making it ideal for shell scripts.' },
      { id: 'm1-t2-single-005', topic: 'grep Intermediate', text: 'What is the function of the -o flag in grep?', options: ['It outputs the matching line numbers only.', 'It prints ONLY the matched text itself, ignoring the rest of the line.', 'It overrides existing files when redirecting output.', 'It omits empty lines from the standard output.'], answer: [1], fact: 'grep -o prints only the matched pattern fragment, discarding the surrounding text on the line.' },
      { id: 'm1-t2-single-006', topic: 'sed Basics', text: 'In the sed command `sed \'s/old/new/\'`, what happens if the word "old" appears three times on a single line?', options: ['All three occurrences are replaced with "new".', 'Only the first occurrence on that line is replaced.', 'The command throws a syntax error requiring the /g flag.', 'The line is deleted and replaced entirely by the word "new".'], answer: [1], fact: 'By default, sed only replaces the first occurrence of a match on a given line unless the global (g) flag is appended.' },
      { id: 'm1-t2-single-007', topic: 'sed Basics', text: 'Which sed flag and suffix combination is recommended to edit a file in-place while keeping a safe copy of the original?', options: ['-e.bak', '-i.bak', '-r.save', '--in-place-backup'], answer: [1], fact: 'Appending .bak to the -i flag (sed -i.bak) modifies the file directly but leaves the untouched original with a .bak extension.' },
      { id: 'm1-t2-single-008', topic: 'sed Intermediate', text: 'When transforming file paths with sed (e.g., changing /var/www to /opt/nginx), what is the cleanest way to write the command?', options: ['Escape every slash using backslashes: s/\\/var\\/www/\\/opt\\/nginx/', 'Use an alternate delimiter like a pipe: s|/var/www|/opt/nginx|', 'Use the -p flag to enable path-mode substitution.', 'Wrap the paths in double quotes instead of forward slashes.'], answer: [1], fact: 'Sed allows any character to act as a delimiter. Using a pipe (|) avoids "leaning toothpick syndrome" when dealing with paths.' },
      { id: 'm1-t2-single-009', topic: 'grep Intermediate', text: 'Which grep command will display the two lines immediately BEFORE a matched pattern?', options: ['grep -A 2', 'grep -C 2', 'grep -B 2', 'grep -p 2'], answer: [2], fact: 'The -B (Before) flag prints context lines preceding the matched pattern.' },
      { id: 'm1-t2-single-010', topic: 'sed Basics', text: 'What does the sed command `sed \'/^$/d\' file.txt` accomplish?', options: ['It deletes lines containing a dollar sign.', 'It deletes lines that start with a caret.', 'It deletes all completely empty lines.', 'It deletes the very first and very last line of the file.'], answer: [2], fact: '^ means start of line and \$ means end of line. ^\$ matches an empty line, and the d command deletes it.' },
      { id: 'm1-t2-single-011', topic: 'History', text: 'In what year was the grep utility written at Bell Labs?', options: ['1969', '1971', '1973', '1977'], answer: [2], fact: 'Ken Thompson wrote grep in 1973, and it shipped in Version 4 UNIX.' },
      { id: 'm1-t2-single-012', topic: 'History', text: 'Who wrote the sed (Stream EDitor) utility at Bell Labs?', options: ['Ken Thompson', 'Lee E. McMahon', 'Doug McIlroy', 'Linus Torvalds'], answer: [1], fact: 'Lee E. McMahon built sed between 1973 and 1974.' },
      { id: 'm1-t2-single-013', topic: 'grep Intermediate', text: 'Which grep flag prints the specified number of lines following each match?', options: ['-B', '-C', '-A', '-F'], answer: [2], fact: 'The -A (After) flag prints context lines following a match.' },
      { id: 'm1-t2-single-014', topic: 'grep Intermediate', text: 'Which grep flag prints the specified number of lines preceding each match?', options: ['-B', '-C', '-A', '-P'], answer: [0], fact: 'The -B (Before) flag prints context lines preceding a match.' },
      { id: 'm1-t2-single-015', topic: 'grep Intermediate', text: 'Which grep flag prints the specified number of lines on both sides of a match?', options: ['-C', '-B', '-A', '-D'], answer: [0], fact: 'The -C (Context) flag prints lines surrounding the matched pattern.' },
      { id: 'm1-t2-single-016', topic: 'grep Intermediate', text: 'When using grep -r, which additional flag limits the output to just the filenames containing the match, rather than the matching lines themselves?', options: ['-n', '-q', '-l', '-o'], answer: [2], fact: 'The -l flag prints only the names of files containing a match.' },
      { id: 'm1-t2-single-017', topic: 'sed Intermediate', text: 'When substituting file paths in sed, why is it beneficial to use an alternate delimiter like `s|old|new|`?', options: ['It increases the execution speed of the stream editor.', 'It prevents sed from interpreting the paths as regex character classes.', 'It avoids the need to escape every forward slash in the path.', 'It automatically enforces global substitution without the g flag.'], answer: [2], fact: 'Using an alternate delimiter avoids the messy escaping of forward slashes (e.g., \\/var\\/www).' },
      { id: 'm1-t2-single-018', topic: 'grep Intermediate', text: 'What does the dollar sign (\$) anchor do in a grep regular expression?', options: ['Matches the pattern only at the beginning of a line.', 'Matches the pattern only at the end of a line.', 'Matches literal dollar signs in the text.', 'Indicates a variable substitution.'], answer: [1], fact: 'The \$ anchor pins the match to the end of the line.' },
      { id: 'm1-t2-single-019', topic: 'grep Intermediate', text: 'What does the caret (^) anchor do in a grep regular expression?', options: ['Matches the pattern only at the beginning of a line.', 'Matches the pattern only at the end of a line.', 'Excludes the pattern from the search.', 'Matches any non-alphanumeric character.'], answer: [0], fact: 'The ^ anchor pins the match to the start of the line.' },
      { id: 'm1-t2-single-020', topic: 'sed Intermediate', text: 'In sed capture groups, how do you refer to the first captured segment in the replacement string?', options: ['\$1', '%1', '\\1', '&1'], answer: [2], fact: 'Captured groups are referenced in the replacement string using \\1, \\2, etc.' },
      { id: 'm1-t2-single-021', topic: 'grep Intermediate', text: 'Which regular expression character class matches any character that is NOT the letter a or r?', options: ['[ar]', '[^ar]', '[!ar]', '[-ar]'], answer: [1], fact: 'A caret (^) inside square brackets flips the set into an exclusion.' },
      { id: 'm1-t2-single-022', topic: 'grep Intermediate', text: 'Which regular expression matches any single digit from 0 to 9?', options: ['[0:9]', '{0-9}', '(0-9)', '[0-9]'], answer: [3], fact: 'Square brackets define a character class, and a hyphen denotes a range.' },
      { id: 'm1-t2-single-023', topic: 'sed Intermediate', text: 'Which sed flag allows you to execute multiple commands in a single pass?', options: ['-m', '-c', '-e', '-x'], answer: [2], fact: 'The -e flag specifies multiple editing commands to apply sequentially.' },
      { id: 'm1-t2-single-024', topic: 'Master Pipeline', text: 'In a process management pipeline, what does the command `cut -d" " -f2` typically extract?', options: ['The second line of the output.', 'The second column separated by spaces.', 'The second character of each line.', 'The last column of the output.'], answer: [1], fact: 'cut -d" " specifies a space delimiter, and -f2 extracts the second field.' },
      { id: 'm1-t2-single-025', topic: 'sed Basics', text: 'What happens if a sed substitution command omits the trailing g flag (e.g., `s/old/new/`)?', options: ['It throws a syntax error.', 'It replaces all occurrences in the file.', 'It replaces only the first occurrence on each line.', 'It prompts the user before every replacement.'], answer: [2], fact: 'Without the g (global) flag, substitution stops after the first match on a line.' }
    ],
    double: [
      { id: 'm1-t2-double-001', topic: 'grep Basics', text: 'Which TWO flags are used together to perform a case-insensitive search that outputs the line numbers of the matches?', options: ['-c', '-i', '-n', '-v'], answer: [1, 2], fact: '-i ignores case, and -n prints the line number before each matched line.' },
      { id: 'm1-t2-double-002', topic: 'grep Intermediate', text: 'Which TWO characters act as line anchors in regular expressions, pinning matches to the start or end of a line?', options: ['*', '^', '\$', '+'], answer: [1, 2], fact: 'The caret (^) anchors to the start of a line, and the dollar sign (\$) anchors to the end.' },
      { id: 'm1-t2-double-003', topic: 'Master Pipeline', text: 'In a standard log analysis pipeline, which TWO commands are often combined to filter for an error code and then rewrite sensitive IP addresses?', options: ['awk', 'grep', 'cut', 'sed'], answer: [1, 3], fact: 'A classic pipeline uses grep to filter the stream and sed to edit or sanitize the resulting text on the fly.' },
      { id: 'm1-t2-double-004', topic: 'grep Intermediate', text: 'Which TWO flags are used together to recursively search all files in a directory and output only the filenames containing a match?', options: ['-r', '-l', '-n', '-o'], answer: [0, 1], fact: '-r searches recursively, and -l suppresses normal output, printing only the filename.' },
      { id: 'm1-t2-double-005', topic: 'Master Pipeline', text: 'Which TWO commands are typically placed after `grep` in a log analysis pipeline to count and rank duplicate entries?', options: ['awk', 'sort', 'uniq', 'cut'], answer: [1, 2], fact: 'sort groups identical lines together, and uniq -c counts them.' },
      { id: 'm1-t2-double-006', topic: 'grep Intermediate', text: 'Which TWO flags print context lines surrounding a grep match?', options: ['-A', '-B', '-i', '-v'], answer: [0, 1], fact: '-A prints lines after the match, and -B prints lines before it.' },
      { id: 'm1-t2-double-007', topic: 'sed Basics', text: 'Which TWO elements are combined in sed to delete completely empty lines?', options: ['/^$/', 'd', 'g', 's/'], answer: [0, 1], fact: '/^$/ matches an empty line, and the d command deletes it.' },
      { id: 'm1-t2-double-008', topic: 'grep Basics', text: 'Which TWO flags enforce strict boundary matching in grep (e.g., matching exact words or exact line starts/ends)?', options: ['-w', '^ and \$ anchors', '-i', '-r'], answer: [0, 1], fact: '-w enforces word boundaries, and anchors enforce line boundaries.' }
    ],
    tf: [
      { id: 'm1-t2-tf-001', topic: 'grep Intermediate', text: 'To search for a pattern within a file, you must first output the file\'s contents using cat and pipe it to grep.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; grep can read files directly (e.g., grep "pattern" file), making cat | grep an unnecessary extra process.' },
      { id: 'm1-t2-tf-002', topic: 'sed Basics', text: 'The sed utility loads the entire target file into system RAM before performing any edits, making it unsuitable for multi-gigabyte log files.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; sed is a Stream Editor that processes text line-by-line, allowing it to edit files much larger than available memory.' },
      { id: 'm1-t2-tf-003', topic: 'grep Basics', text: 'The grep -v command can be used to filter out noise, such as stripping comment lines from a configuration file.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; -v inverts the match, showing everything EXCEPT lines containing the pattern.' },
      { id: 'm1-t2-tf-004', topic: 'sed Intermediate', text: 'You can execute multiple different substitution commands in a single sed pass by chaining them with the -e flag.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; the -e flag allows multiple operations to be applied sequentially to the same stream.' },
      { id: 'm1-t2-tf-005', topic: 'sed Basics', text: 'If the -i flag is omitted, sed will only print its changes to standard output and leave the original file untouched.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; sed writes to standard output by default unless told to edit in-place with -i.' },
      { id: 'm1-t2-tf-006', topic: 'grep Intermediate', text: 'The grep utility requires the -E flag to perform basic literal string searches.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; -E is only required for extended regular expressions like OR operators and quantifiers.' },
      { id: 'm1-t2-tf-007', topic: 'sed Intermediate', text: 'Sed substitutions strictly require the forward slash (/) as a delimiter and will crash if a pipe (|) is used.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; sed accepts alternate delimiters like pipes (|) to improve readability.' },
      { id: 'm1-t2-tf-008', topic: 'grep Intermediate', text: 'The grep -q command prints the matched text to the screen but suppresses the line numbers.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; -q prints absolutely nothing and sets the exit status only.' },
      { id: 'm1-t2-tf-009', topic: 'History', text: 'The older commands egrep and fgrep are deprecated on modern systems in favor of grep -E and grep -F.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; modern systems warn against using the legacy egrep/fgrep commands.' },
      { id: 'm1-t2-tf-010', topic: 'History', text: 'Doug McIlroy credited the creation of grep with helping to cement the UNIX philosophy of specialized, one-pass tools.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; McIlroy requested the regex recognizer be lifted out of the ed editor to form a standalone tool.' }
    ],
    identification: [
      { id: 'm1-t2-identification-001', topic: 'History', text: 'Who wrote grep at Bell Labs in 1973?', answer: ['KEN THOMPSON'], fact: 'Ken Thompson created grep for Version 4 UNIX.' },
      { id: 'm1-t2-identification-002', topic: 'History', text: 'What does the acronym SED stand for?', answer: ['STREAM EDITOR'], fact: 'sed stands for Stream EDitor, built by Lee E. McMahon.' },
      { id: 'm1-t2-identification-003', topic: 'grep Intermediate', text: 'What grep flag enables the use of OR operators (|) and quantifiers (+, ?) in your search pattern?', answer: ['-E', 'E'], fact: 'The -E flag enables Extended regular expressions.' },
      { id: 'm1-t2-identification-004', topic: 'grep Intermediate', text: 'What grep flag descends into every subdirectory to search files, printing the filename beside each hit?', answer: ['-R', 'R', '-r', 'r'], fact: 'The -r flag performs a recursive search.' },
      { id: 'm1-t2-identification-005', topic: 'sed Basics', text: 'What letter is appended to a sed substitution command to ensure all occurrences on a single line are replaced?', answer: ['G', 'g'], fact: 'The g flag stands for global substitution on the current line.' },
      { id: 'm1-t2-identification-006', topic: 'grep Basics', text: 'What command character inside regex brackets (e.g., [^abc]) transforms the set into an exclusion?', answer: ['^', 'CARET'], fact: 'A caret inside brackets negates the character class.' },
      { id: 'm1-t2-identification-007', topic: 'sed Basics', text: 'What sed flag modifies the file directly on the disk rather than writing to standard output?', answer: ['-I', 'I', '-i', 'i'], fact: 'The -i flag performs in-place editing.' },
      { id: 'm1-t2-identification-008', topic: 'grep Intermediate', text: 'What grep flag prints trailing context lines (lines following the match)?', answer: ['-A', 'A'], fact: 'The -A flag stands for After.' },
      { id: 'm1-t2-identification-009', topic: 'grep Intermediate', text: 'What grep flag prints leading context lines (lines preceding the match)?', answer: ['-B', 'B'], fact: 'The -B flag stands for Before.' },
      { id: 'm1-t2-identification-010', topic: 'grep Intermediate', text: 'What grep flag prints lines both before and after a match?', answer: ['-C', 'C'], fact: 'The -C flag stands for Context.' },
      { id: 'm1-t2-identification-011', topic: 'sed Basics', text: 'What extension is automatically appended to the original filename when using sed -i.bak?', answer: ['.BAK', 'BAK'], fact: 'The -i.bak flag creates a backup file with a .bak extension.' },
      { id: 'm1-t2-identification-012', topic: 'sed Intermediate', text: 'In a sed replacement string, what syntax references the second captured group?', answer: ['\\2'], fact: 'Backslashes followed by numbers reference captured groups.' },
      { id: 'm1-t2-identification-013', topic: 'grep Intermediate', text: 'What grep flag suppresses normal output and prints only the names of files containing matches?', answer: ['-L', 'L', '-l', 'l'], fact: 'The -l flag outputs matching filenames only.' },
      { id: 'm1-t2-identification-014', topic: 'sed Basics', text: 'What single letter represents the delete command in sed?', answer: ['D', 'd'], fact: 'The d command deletes lines matching the preceding pattern.' },
      { id: 'm1-t2-identification-015', topic: 'grep Basics', text: 'What grep flag inverts the match logic, returning only lines that do NOT contain the pattern?', answer: ['-V', 'V', '-v', 'v'], fact: 'The -v flag inverts the search criteria.' },
      { id: 'm1-t2-identification-016', topic: 'sed Intermediate', text: 'What sed flag allows the execution of multiple editing commands in one pass?', answer: ['-E', 'E', '-e', 'e'], fact: 'The -e flag chains commands together.' },
      { id: 'm1-t2-identification-017', topic: 'grep Intermediate', text: 'What symbols define a character class in a regular expression, matching any single character contained within?', answer: ['[ ]', 'SQUARE BRACKETS', 'BRACKETS'], fact: 'Square brackets denote a character class.' }
    ],
    sequence: [
      { id: 'm1-t2-sequence-001', topic: 'Master Pipeline', text: 'Arrange the steps in the pipeline used to find the most frequent attacker IPs generating 404 errors.', steps: ['Use grep "404\$" to isolate failed request lines in the log.', 'Use grep -oE to extract only the IP address strings.', 'Use sort to organize the extracted IPs alphabetically.', 'Use uniq -c to count adjacent duplicate IPs.', 'Use sort -nr to order the counts numerically in reverse.'], answer: [0, 1, 2, 3, 4], fact: 'The logical flow is: filter rows -> extract data -> group data -> count duplicates -> rank results.' },
      { id: 'm1-t2-sequence-002', topic: 'Master Pipeline', text: 'Order the pipeline commands to extract process IDs of an sshd service and terminate them.', steps: ['Run ps aux to list all running system processes.', 'Run grep sshd to filter for the target service.', 'Run grep -v grep to exclude your own search command.', 'Run sed to collapse multiple spaces into a single delimiter.', 'Run cut to extract the PID column, then xargs kill.'], answer: [0, 1, 2, 3, 4], fact: 'A legacy PID extraction pipeline filters the process list, sanitizes the spacing, and extracts the target column.' },
      { id: 'm1-t2-sequence-003', topic: 'Master Pipeline', text: 'Order the steps in a log sanitization pipeline designed to publish a safe extract of web requests.', steps: ['Use grep -v to filter out and drop internal subnet traffic.', 'Pipe the surviving lines into a second grep command.', 'Use grep -oE to extract only the HTTP verb and status code, discarding client IPs.', 'Use the > operator to redirect the sanitized output into a public log file.'], answer: [0, 1, 2, 3], fact: 'The pipeline must remove restricted records entirely before extracting fragments from the survivors.' },
      { id: 'm1-t2-sequence-004', topic: 'sed Intermediate', text: 'Order the logical phases of a sed capture group substitution.', steps: ['Match the entire target line or string using regular expressions.', 'Isolate specific segments of the match using parentheses ( ) to form capture groups.', 'Construct the replacement string using reference markers like \\1 and \\2.', 'Output the reordered or transformed string.'], answer: [0, 1, 2, 3], fact: 'Sed must match, capture into memory, construct the replacement, and output the result.' },
      { id: 'm1-t2-sequence-005', topic: 'Master Pipeline', text: 'Order the steps to parse a configuration file by stripping noise before editing.', steps: ['Use grep -vE "^#|^\$" to drop all comments and blank lines.', 'Pipe the cleanly parsed configuration directives into sed.', 'Use sed to substitute specific directive values (e.g., changing port numbers).', 'Redirect the final hardened configuration to a new file.'], answer: [0, 1, 2, 3], fact: 'Removing noise (comments/blanks) first makes subsequent stream editing cleaner and more predictable.' }
    ]
  }
};