window.quizTopics = window.quizTopics || {};

window.quizTopics.topic1 = {
  id: 'topic1',
  label: 'Topic 1',
  title: 'Foundations of System Administration',
  description: 'Roles, lifecycle, Linux history, the filesystem, and the 35 essential commands',
  questions: {
    single: [
      { id: 'm1-t1-single-001', topic: 'Roles & Lifecycle', text: 'During which system lifecycle stage does a system administrator typically expand storage, apply patches, and replace failing parts?', options: ['Deploy', 'Configure', 'Operate', 'Maintain'], answer: [3], fact: 'Maintenance involves patching, replacing parts, and tuning performance while the service is active.' },
      { id: 'm1-t1-single-002', topic: 'CLI vs GUI', text: 'Why is the command-line interface (CLI) considered the working language of system administration over the graphical user interface (GUI)?', options: ['It requires significantly fewer hardware resources to render.', 'It is scriptable, remote-friendly, precise, and reproducible.', 'It natively encrypts all commands sent across the network.', 'It prevents users from accidentally deleting system files.'], answer: [1], fact: 'The CLI is preferred because it allows for automation, remote access, and precise, reproducible configurations.' },
      { id: 'm1-t1-single-003', topic: 'Linux History', text: 'Who announced the GNU Project in 1983 with the goal of building a free, UNIX-compatible operating system?', options: ['Ken Thompson', 'Linus Torvalds', 'Richard Stallman', 'Andrew Tanenbaum'], answer: [2], fact: 'Richard Stallman announced GNU ("GNU\'s Not UNIX") to create a free OS ecosystem.' },
      { id: 'm1-t1-single-004', topic: 'Linux History', text: 'Which operating system, released in 1987 for teaching purposes, provided source code that Linus Torvalds read before developing the Linux kernel?', options: ['MINIX', 'System V UNIX', 'FreeBSD', 'Debian'], answer: [0], fact: 'Andrew Tanenbaum released MINIX, whose source code directly influenced Linus Torvalds.' },
      { id: 'm1-t1-single-005', topic: 'Linux vs UNIX', text: 'What is the primary distinction between Linux and true UNIX?', options: ['Linux lacks a hierarchical filesystem tree.', 'Linux does not support multiple concurrent users.', 'Linux is UNIX-like, differing primarily in licensing and kernel architecture.', 'Linux utilizes a graphical command shell by default.'], answer: [2], fact: 'Linux shares ancestry and philosophy with UNIX but differs in licensing, kernel design, and open-source availability.' },
      { id: 'm1-t1-single-006', topic: 'Distributions', text: 'In practice, choosing a specific Linux distribution family (such as Debian vs. Red Hat) is largely a choice of what?', options: ['The desktop environment', 'The package manager and repository ecosystem', 'The default shell interpreter', 'The physical filesystem standard'], answer: [1], fact: 'A distribution is heavily defined by its package manager (e.g., apt, dnf) and curated software repositories.' },
      { id: 'm1-t1-single-007', topic: 'Essential Commands', text: 'Which command prints the absolute physical location of the directory, avoiding all symbolic links?', options: ['pwd -L', 'pwd -P', 'cd -', 'ls -l'], answer: [1], fact: 'The -P flag for pwd prints the actual physical path instead of the logical path.' },
      { id: 'm1-t1-single-008', topic: 'Essential Commands', text: 'Which flag for the rm command prompts for confirmation before every deletion, making it safer for nervous administrators?', options: ['-r', '-f', '-v', '-i'], answer: [3], fact: 'The -i (interactive) flag forces rm to ask for confirmation before deleting files.' },
      { id: 'm1-t1-single-009', topic: 'Essential Commands', text: 'What will the command touch -m file.txt accomplish?', options: ['It creates a file with a specified size in megabytes.', 'It changes only the file\'s modification time, leaving access time alone.', 'It alters the file\'s permissions (mode) upon creation.', 'It moves the file to a temporary directory.'], answer: [1], fact: 'The -m flag in touch updates only the modification timestamp.' },
      { id: 'm1-t1-single-010', topic: 'Essential Commands', text: 'While viewing running processes in top, which keystroke re-sorts the list to show the highest memory consumers at the top?', options: ['k', 'Shift+P', 'Shift+M', 'q'], answer: [2], fact: 'Shift+M in top sorts the active processes by memory consumption.' },
      { id: 'm1-t1-single-011', topic: 'Essential Commands', text: 'Which command helps diagnose a scenario where a disk has free space but cannot store new files due to a lack of available filesystem objects?', options: ['df -h', 'df -T', 'du -sh', 'df -i'], answer: [3], fact: 'df -i shows inode usage, which is critical when a filesystem runs out of inodes despite having free block space.' },
      { id: 'm1-t1-single-012', topic: 'Essential Commands', text: 'Which command displays system memory values automatically scaled to the shortest three-digit unit (e.g., K, M, G)?', options: ['free -m', 'free -h', 'htop --memory', 'df -h'], answer: [1], fact: 'free -h makes memory statistics human-readable.' },
      { id: 'm1-t1-single-013', topic: 'Essential Commands', text: 'What uname flag prints the kernel release version, which is essential when compiling or installing kernel modules?', options: ['-a', '-m', '-r', '-n'], answer: [2], fact: 'uname -r outputs the specific kernel release version.' },
      { id: 'm1-t1-single-014', topic: 'Essential Commands', text: 'In the less pager, what keystroke jumps immediately to the very bottom of the file?', options: ['/', 'q', 'g', 'Shift+G'], answer: [3], fact: 'Shift+G jumps to the end of the file in less.' },
      { id: 'm1-t1-single-015', topic: 'Essential Commands', text: 'Which grep flag is used to perform a case-insensitive search?', options: ['-v', '-i', '-r', '-n'], answer: [1], fact: 'The -i flag makes grep match regardless of upper or lower case.' },
      { id: 'm1-t1-single-016', topic: 'Essential Commands', text: 'Which tail flag continues to watch a file and handles situations where the file is rotated or replaced by the system?', options: ['-f', '-F', '-n', '--pid'], answer: [1], fact: 'tail -F follows a file by name and retries if it is rotated, unlike the standard -f.' },
      { id: 'm1-t1-single-017', topic: 'Essential Commands', text: 'In awk, what built-in variable specifically refers to the last field of the current line?', options: ['BEGIN', '$1', '$NF', '-F'], answer: [2], fact: '$NF represents the "Number of Fields," effectively targeting the final column.' },
      { id: 'm1-t1-single-018', topic: 'Essential Commands', text: 'Which sed command edits a file directly on disk instead of just outputting the changes to the screen?', options: ['sed -n', 'sed -i', 'sed s/old/new/g', 'sed -d'], answer: [1], fact: 'The -i (in-place) flag applies transformations directly to the target file.' },
      { id: 'm1-t1-single-019', topic: 'Essential Commands', text: 'Which ip subcommand is used to show or manipulate the IP routing table?', options: ['addr', 'link', 'route', '-br'], answer: [2], fact: 'ip route manages and displays system routing information.' },
      { id: 'm1-t1-single-020', topic: 'Essential Commands', text: 'Which command retrieves files non-interactively using protocols like HTTP and FTP and supports recursive website downloading?', options: ['curl', 'ping', 'wget', 'ss'], answer: [2], fact: 'wget is a robust non-interactive downloader that supports recursive operations.' },
      { id: 'm1-t1-single-021', topic: 'Essential Commands', text: 'What curl flag is used to fetch only the HTTP headers to check if a URL exists without downloading the content?', options: ['-O', '-d', '-X POST', '-I'], answer: [3], fact: 'curl -I fetches only the document headers.' },
      { id: 'm1-t1-single-022', topic: 'Essential Commands', text: 'In the ss and netstat commands, what does the -p flag accomplish?', options: ['It displays only TCP connections.', 'It restricts output to listening sockets.', 'It shows the PID and name of the program using the socket.', 'It prevents resolving port numbers to hostnames.'], answer: [2], fact: 'The -p flag identifies the process attached to the network port.' },
      { id: 'm1-t1-single-023', topic: 'Essential Commands', text: 'What is the numeric mode to set read, write, and execute for the owner, and read and execute for the group and others?', options: ['777', '644', '755', '700'], answer: [2], fact: '755 grants rwx (7) to owner, rx (5) to group, and rx (5) to others.' },
      { id: 'm1-t1-single-024', topic: 'Essential Commands', text: 'Which kill signal is the polite termination signal (SIGTERM) that allows a process to clean up before exiting?', options: ['-9', '-15', '-HUP', '-1'], answer: [1], fact: 'kill -15 sends SIGTERM, asking the application to exit gracefully.' },
      { id: 'm1-t1-single-025', topic: 'Essential Commands', text: 'Which systemctl command configures a service to automatically start when the system boots?', options: ['start', 'status', 'restart', 'enable'], answer: [3], fact: 'systemctl enable creates symlinks to ensure a service starts at boot time.' }
    ],
    double: [
      { id: 'm1-t1-double-001', topic: 'Roles & Lifecycle', text: 'Which TWO responsibilities fall under the "Security & Access Control" role of a system administrator?', options: ['Managing SSH keys and permissions', 'Auditing logs for unauthorized access', 'Replacing failing physical hardware', 'Writing procurement requirements'], answer: [0, 1], fact: 'Security management includes managing access credentials (SSH, permissions) and log auditing.' },
      { id: 'm1-t1-double-002', topic: 'Linux History', text: 'Which TWO projects or operating systems provided the direct foundation and user-space tools that made the first Linux kernel a complete operating system?', options: ['The GNU Project', 'System V UNIX', 'Windows NT', 'MINIX'], answer: [0, 3], fact: 'Linus Torvalds read MINIX source code, and combined his kernel with GNU tools to create a full OS.' },
      { id: 'm1-t1-double-003', topic: 'Essential Commands', text: 'Which TWO commands are primarily used to measure storage utilization on disks and directories?', options: ['df', 'du', 'free', 'top'], answer: [0, 1], fact: 'df checks filesystem disk space, while du estimates directory sizes.' },
      { id: 'm1-t1-double-004', topic: 'Essential Commands', text: 'Which TWO commands are modern replacements for inspecting network interfaces and socket statistics?', options: ['ip', 'ss', 'ifconfig', 'netstat'], answer: [0, 1], fact: 'ip replaces ifconfig, and ss is the modern alternative to netstat.' },
      { id: 'm1-t1-double-005', topic: 'Essential Commands', text: 'Which TWO text processing tools are considered powerful pattern-scanning languages and stream editors rather than simple pagers?', options: ['awk', 'sed', 'less', 'cat'], answer: [0, 1], fact: 'awk and sed parse, filter, and transform text streams dynamically.' },
      { id: 'm1-t1-double-006', topic: 'Essential Commands', text: 'Which TWO commands are best suited for monitoring live logs or processes in real-time as they change?', options: ['tail -f', 'top', 'head -n 20', 'cat'], answer: [0, 1], fact: 'tail -f continuously follows file appends, and top provides a real-time process dashboard.' }
    ],
    tf: [
      { id: 'm1-t1-tf-001', topic: 'Linux History', text: 'Linus Torvalds explicitly designed the first Linux kernel in 1991 to be a massive, professional operating system that would replace UNIX.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; Torvalds famously called it "just a hobby, won\'t be big and professional."' },
      { id: 'm1-t1-tf-002', topic: 'Linux vs UNIX', text: 'Linux is officially certified as UNIX because it shares the exact same kernel architecture as the original Bell Labs UNIX.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; Linux is UNIX-like. It shares philosophy but was written from scratch and has a different licensing model.' },
      { id: 'm1-t1-tf-003', topic: 'Essential Commands', text: 'The rm command permanently deletes files; there is no recycle bin built into standard CLI deletion.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; in the CLI, rm deletion is final.' },
      { id: 'm1-t1-tf-004', topic: 'Essential Commands', text: 'The top command can be run in a batch mode (-n 1) that outputs one single iteration and then exits, making it useful for scripts.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; top -n 1 captures a single snapshot of system performance.' },
      { id: 'm1-t1-tf-005', topic: 'Essential Commands', text: 'The command kill -9 sends a signal that forces immediate termination without giving the process time to save data.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; SIGKILL (-9) forces the kernel to instantly terminate the process.' },
      { id: 'm1-t1-tf-006', topic: 'Essential Commands', text: 'By default, the chmod command changes both the file\'s permissions and its owning user.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; chmod only changes permissions. The chown command changes ownership.' },
      { id: 'm1-t1-tf-007', topic: 'Essential Commands', text: 'The journalctl command is used specifically to query and display logs collected by systemd.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; journalctl is the dedicated interface for systemd-journald logs.' },
      { id: 'm1-t1-tf-008', topic: 'Filesystem', text: 'Like Windows, Linux utilizes drive letters (like C: and D:) to organize different physical disks.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; Linux uses a single rooted tree starting at /.' }
    ],
    identification: [
      { id: 'm1-t1-identification-001', topic: 'Linux History', text: 'In what year was the original UNIX developed at AT&T Bell Labs?', answer: ['1969'], fact: 'UNIX was created by Ken Thompson and Dennis Ritchie in 1969.' },
      { id: 'm1-t1-identification-002', topic: 'Linux History', text: 'Who announced the GNU Project in 1983 to build a free operating system?', answer: ['RICHARD STALLMAN'], fact: 'Richard Stallman founded the GNU Project.' },
      { id: 'm1-t1-identification-003', topic: 'Linux History', text: 'What teaching operating system did Andrew Tanenbaum release in 1987?', answer: ['MINIX'], fact: 'MINIX was a lightweight UNIX-like OS used for education.' },
      { id: 'm1-t1-identification-004', topic: 'Filesystem', text: 'In Linux, every file and device lives under a single root directory represented by what character?', answer: ['/'], fact: 'The forward slash represents the root of the filesystem.' },
      { id: 'm1-t1-identification-005', topic: 'Essential Commands', text: 'What command prints the absolute pathname of your current working directory?', answer: ['PWD'], fact: 'pwd stands for Print Working Directory.' },
      { id: 'm1-t1-identification-006', topic: 'Essential Commands', text: 'Which touch flag lets you assign a specific historical timestamp to a file?', answer: ['-T'], fact: 'touch -t allows setting a precise custom timestamp.' },
      { id: 'm1-t1-identification-007', topic: 'Essential Commands', text: 'What interactive command displays processes in a hierarchical tree and a colorful scrollable list?', answer: ['HTOP'], fact: 'htop is a colorful, enhanced alternative to top.' },
      { id: 'm1-t1-identification-008', topic: 'Essential Commands', text: 'What flag must be used with the cp command to duplicate a directory and all its contents?', answer: ['-R', 'R', '-r', 'r'], fact: 'The recursive flag is required to copy folders.' },
      { id: 'm1-t1-identification-009', topic: 'Essential Commands', text: 'What memory monitoring command takes the -h flag to display values in Megabytes or Gigabytes?', answer: ['FREE'], fact: 'free -h displays memory utilization clearly.' },
      { id: 'm1-t1-identification-010', topic: 'Essential Commands', text: 'Which command outputs how long the system has been running, user counts, and load averages?', answer: ['UPTIME'], fact: 'uptime provides run duration and system load metrics.' },
      { id: 'm1-t1-identification-011', topic: 'Essential Commands', text: 'Which text processing command reads files and outputs everything directly to the terminal without pausing?', answer: ['CAT'], fact: 'cat concatenates and prints entire files instantly.' },
      { id: 'm1-t1-identification-012', topic: 'Essential Commands', text: 'What command opens a file in a scrollable pager, allowing you to move backward and search without loading the whole file into memory?', answer: ['LESS'], fact: 'less is a pager ideal for large files.' },
      { id: 'm1-t1-identification-013', topic: 'Essential Commands', text: 'Which grep flag performs a case-insensitive search?', answer: ['-I', 'I', '-i', 'i'], fact: 'grep -i ignores casing when matching patterns.' },
      { id: 'm1-t1-identification-014', topic: 'Essential Commands', text: 'Which command prints the first 10 lines of a file by default?', answer: ['HEAD'], fact: 'head displays the beginning of a file.' },
      { id: 'm1-t1-identification-015', topic: 'Essential Commands', text: 'In awk, what flag changes the delimiter from whitespace to a different character like a colon?', answer: ['-F', 'F', '-f', 'f'], fact: 'The -F flag defines the field separator.' },
      { id: 'm1-t1-identification-016', topic: 'Essential Commands', text: 'Which command is heavily used for downloading files non-interactively using HTTP or FTP protocols?', answer: ['WGET'], fact: 'wget handles non-interactive background downloads.' },
      { id: 'm1-t1-identification-017', topic: 'Essential Commands', text: 'Which tool is often used to transfer data to or from APIs and can send custom HTTP methods like POST?', answer: ['CURL'], fact: 'curl is the standard tool for HTTP requests and API testing.' },
      { id: 'm1-t1-identification-018', topic: 'Essential Commands', text: 'What command modifies file access rights for the owner, group, and others?', answer: ['CHMOD'], fact: 'chmod changes file mode bits.' },
      { id: 'm1-t1-identification-019', topic: 'Essential Commands', text: 'What command executes a single instruction with superuser (root) privileges?', answer: ['SUDO'], fact: 'sudo temporarily escalates privileges.' },
      { id: 'm1-t1-identification-020', topic: 'Essential Commands', text: 'Which combination of flags for the ps command displays all system processes using BSD syntax (often piped to grep)?', answer: ['AUX', 'aux'], fact: 'ps aux provides a comprehensive snapshot of all running processes.' },
      { id: 'm1-t1-identification-021', topic: 'Essential Commands', text: 'Which command sends signals to running processes, usually to terminate them by PID?', answer: ['KILL'], fact: 'kill sends signals like SIGTERM or SIGKILL to processes.' },
      { id: 'm1-t1-identification-022', topic: 'Essential Commands', text: 'What command is used to introspect and control the state of systemd services (start, stop, enable)?', answer: ['SYSTEMCTL'], fact: 'systemctl manages systemd units.' },
      { id: 'm1-t1-identification-023', topic: 'Essential Commands', text: 'What command queries logs collected by systemd-journald?', answer: ['JOURNALCTL'], fact: 'journalctl reads binary systemd logs.' }
    ],
    sequence: [
      { id: 'm1-t1-sequence-001', topic: 'Roles & Lifecycle', text: 'Order the standard stages of a system\'s lifecycle as managed by an administrator.', steps: ['Plan (Define requirements and estimate capacity)', 'Deploy (Install the OS and configure network)', 'Configure (Harden the system and apply baselines)', 'Operate (Serve users while monitoring)', 'Maintain (Apply patches and expand storage)', 'Retire (Wipe data and decommission hardware)'], answer: [0, 1, 2, 3, 4, 5], fact: 'A system always passes from planning, to deployment, configuration, operation, maintenance, and finally retirement.' },
      { id: 'm1-t1-sequence-002', topic: 'Essential Commands', text: 'Order the steps an administrator might take to safely backup a directory and verify its storage size.', steps: ['Run du -sh on the target directory to check its size.', 'Run mkdir to create a new backup folder.', 'Run cp -rv to recursively copy files to the new folder.', 'Run ls -lh on the new folder to verify the contents.'], answer: [0, 1, 2, 3], fact: 'First evaluate space, make a destination, execute the copy, and verify the result.' },
      { id: 'm1-t1-sequence-003', topic: 'Essential Commands', text: 'Order the typical commands used to initialize and persist a new systemd service.', steps: ['Run sudo systemctl start [service]', 'Run sudo systemctl status [service] to verify it is running', 'Run sudo systemctl enable [service] to persist it on boot', 'Run sudo journalctl -u [service] to check for startup errors'], answer: [0, 1, 2, 3], fact: 'A service must be started, verified, set to auto-start, and audited for runtime errors.' }
    ]
  }
};
