window.quizTopics = window.quizTopics || {};

window.quizTopics.topic3 = {
  id: 'topic3',
  label: 'Topic 3',
  title: 'File Permissions & Ownership',
  description: 'Linux access control, ownership, and advanced text processing with awk',
  questions: {
    single: [
      { id: 'm1-t3-single-001', topic: 'awk History', text: 'What do the letters in "awk" stand for?', options: ['Advanced Word Keyword', 'Aho, Weinberger, Kernighan', 'Automated Workflow Kernel', 'Array Writer Kit'], answer: [1], fact: 'awk is named after the last initials of its creators at Bell Labs: Alfred Aho, Peter Weinberger, and Brian Kernighan.' },
      { id: 'm1-t3-single-002', topic: 'awk Basics', text: 'By default, what character does awk use to separate fields (columns) in a text stream?', options: ['Commas', 'Tabs', 'Whitespace', 'Colons'], answer: [2], fact: 'By default, awk automatically splits lines into fields based on whitespace (spaces or tabs).' },
      { id: 'm1-t3-single-003', topic: 'awk Basics', text: 'Which awk flag allows you to change the field delimiter to a colon for parsing files like /etc/passwd?', options: ['-d:', '-c:', '-s:', '-F:'], answer: [3], fact: 'The -F flag defines a custom field separator for awk to split columns.' },
      { id: 'm1-t3-single-004', topic: 'awk Intermediate', text: 'In awk, what does the built-in variable NR represent?', options: ['Number of Records (the current line number)', 'Number of Fields (columns in the current line)', 'Next Record (skip to the next line)', 'Null Result (a failed pattern match)'], answer: [0], fact: 'NR tracks the Number of Records, which corresponds to the current line number being processed.' },
      { id: 'm1-t3-single-005', topic: 'awk Intermediate', text: 'In awk, what does the built-in variable NF represent?', options: ['Number of Files being processed', 'Number of Fields (total columns in the current line)', 'Next Function call', 'Numerical Format'], answer: [1], fact: 'NF counts the Number of Fields (columns) found on the current line.' },
      { id: 'm1-t3-single-006', topic: 'awk Intermediate', text: 'When processing a file, when does the awk END {} block execute?', options: ['After every single line is processed', 'Only if the pattern match fails', 'Exactly once, after the final line of the file is processed', 'Exactly once, before the first line is read'], answer: [2], fact: 'The END block runs after all lines are processed, making it perfect for printing final totals or footers.' },
      { id: 'm1-t3-single-007', topic: 'awk Intermediate', text: 'Which awk syntax checks if the 3rd column exactly matches the string "Sales", rather than just containing it?', options: ['awk \'\$3 == "Sales"\'', 'awk \'\$3 ~ "Sales"\'', 'awk \'/Sales/\'', 'awk \'\$3 = "Sales"\''], answer: [0], fact: 'The == operator performs an exact string match against a specific field, preventing partial matches.' },
      { id: 'm1-t3-single-008', topic: 'awk Advanced', text: 'Which awk function is used to output perfectly aligned, formatted tables with exact spacing?', options: ['format()', 'print_table', 'printf', 'echo_aligned'], answer: [2], fact: 'printf replaces standard print when strict formatting, alignment, and spacing (e.g., %-10s) are required.' },
      { id: 'm1-t3-single-009', topic: 'awk Advanced', text: 'What does the awk function `substr($2, 1, 3)` accomplish?', options: ['It subtracts the value of column 1 from column 3.', 'It extracts characters from the 2nd column, starting at position 1, for 3 characters.', 'It substitutes the first 3 spaces with underscores in the 2nd column.', 'It prints columns 1, 2, and 3 in reverse order.'], answer: [1], fact: 'substr() extracts substrings, taking the target string, the starting index, and the length.' },
      { id: 'm1-t3-single-010', topic: 'Master Pipeline', text: 'When executing the pipeline `awk -F: \'{print $2}\' file | sed \'s/ /_/g\'`, what is the final outcome?', options: ['It extracts the second column and deletes all empty spaces.', 'It extracts the second column and globally replaces spaces with underscores.', 'It replaces colons with underscores in the second column.', 'It prints the file backwards, replacing spaces.'], answer: [1], fact: 'The pipeline extracts names with awk, then uses sed to substitute whitespace with underscores.' },
      { id: 'm1-t3-single-011', topic: 'History', text: 'In what year was the awk utility created?', options: ['1969', '1973', '1977', '1983'], answer: [2], fact: 'Alfred Aho, Peter Weinberger, and Brian Kernighan created awk in 1977.' },
      { id: 'm1-t3-single-012', topic: 'History', text: 'At which research institution was awk developed?', options: ['MIT', 'Bell Labs', 'Berkeley', 'CERN'], answer: [1], fact: 'awk was created by researchers at Bell Labs.' },
      { id: 'm1-t3-single-013', topic: 'awk Intermediate', text: 'How do you structure a regex pattern match in awk so an action only applies to lines containing "Engineering"?', options: ['"Engineering" {action}', '/Engineering/ {action}', '*Engineering* {action}', '-m Engineering {action}'], answer: [1], fact: 'Awk uses forward slashes to enclose regex patterns (e.g., /Engineering/).' },
      { id: 'm1-t3-single-014', topic: 'awk Basics', text: 'What variable in awk represents the entire, un-split current line?', options: ['$ALL', '\$1', '\$0', '$LINE'], answer: [2], fact: '\$0 represents the entire raw line before field extraction.' },
      { id: 'm1-t3-single-015', topic: 'awk Intermediate', text: 'Which operator is used in awk to verify that a specific field is an exact string match, rather than a partial regex match?', options: ['~', '=', '==', '=>'], answer: [2], fact: 'The == operator checks for absolute equality, unlike the ~ regex match operator.' },
      { id: 'm1-t3-single-016', topic: 'awk Intermediate', text: 'Which keyword allows awk to execute different actions based on a condition within the action block?', options: ['when', 'case', 'if', 'test'], answer: [2], fact: 'awk supports standard if/else conditional logic.' },
      { id: 'm1-t3-single-017', topic: 'awk Advanced', text: 'In the awk printf function, what does the format string `%-10s` dictate?', options: ['A number truncated to 10 decimal places.', 'A right-aligned string of 10 characters.', 'A left-aligned string padded to 10 characters.', 'A substring that skips the first 10 characters.'], answer: [2], fact: 'The minus sign dictates left-alignment, and the 10 enforces a character width.' },
      { id: 'm1-t3-single-018', topic: 'awk Advanced', text: 'In the awk substr() function, what index number represents the very first character of the string?', options: ['0', '1', '-1', 'N'], answer: [1], fact: 'Unlike many programming languages, awk string indexes begin at 1, not 0.' },
      { id: 'm1-t3-single-019', topic: 'awk Advanced', text: 'How do you increment a custom counter variable named "count" for every matching line in awk?', options: ['count =+ 1', 'count++', 'let count = count + 1', 'count.add()'], answer: [1], fact: 'The ++ operator increments the variable by 1 for each evaluation.' },
      { id: 'm1-t3-single-020', topic: 'Permissions', text: 'In the Linux permission model, what do the letters "rwx" stand for?', options: ['Root, Window, X11', 'Read, Write, Execute', 'Row, Width, Extent', 'Remote, Web, XML'], answer: [1], fact: 'Permissions are broken down into Read, Write, and Execute bits.' },
      { id: 'm1-t3-single-021', topic: 'Permissions', text: 'What is the purpose of the setuid special permission bit?', options: ['It allows the file to be executed with the privileges of the file\'s owner.', 'It prevents the file from ever being deleted.', 'It restricts execution to members of the root group.', 'It encrypts the executable binary on disk.'], answer: [0], fact: 'Setuid elevates the executing user\'s privileges to match the file owner\'s privileges during execution.' },
      { id: 'm1-t3-single-022', topic: 'Permissions', text: 'What is the purpose of the sticky bit on a directory?', options: ['It forces all new files to inherit the group of the directory.', 'It prevents users from deleting files they do not own within that directory.', 'It makes the directory immutable to the root user.', 'It compresses files automatically upon creation.'], answer: [1], fact: 'The sticky bit restricts file deletion inside a shared directory strictly to the file owners.' },
      { id: 'm1-t3-single-023', topic: 'Master Pipeline', text: 'When piping awk output into sed (e.g., `awk \'{print $2}\' | sed \'s/ /_/g\'`), what is the primary goal?', options: ['To filter out numeric columns before counting them.', 'To extract a specific column and then reformat its text content.', 'To sort the extracted column alphabetically.', 'To delete the extracted column from the original file.'], answer: [1], fact: 'Awk extracts the target column, and sed formats it (e.g., replacing spaces).' },
      { id: 'm1-t3-single-024', topic: 'awk Intermediate', text: 'What is the key difference between the BEGIN block and the END block in awk?', options: ['BEGIN executes if a match is found; END executes if no match is found.', 'BEGIN runs before the file is processed; END runs after all lines are processed.', 'BEGIN formats strings; END performs math.', 'BEGIN runs for the first line only; END runs for the last line only.'], answer: [1], fact: 'BEGIN and END blocks bracket the main line-by-line processing loop.' },
      { id: 'm1-t3-single-025', topic: 'Permissions', text: 'Which command is used to change the user owner and group owner of a file simultaneously?', options: ['chmod', 'chown', 'chgrp', 'usermod'], answer: [1], fact: 'chown changes file ownership and can target both user and group (e.g., chown user:group).' }
    ],
    double: [
      { id: 'm1-t3-double-001', topic: 'awk Intermediate', text: 'Which TWO mathematical/logical operations are natively supported inside awk action blocks without invoking external tools?', options: ['Summing columns with +=', 'Evaluating if/else conditionals', 'Compiling C source code', 'Rebooting the system kernel'], answer: [0, 1], fact: 'awk is a full programming language that supports variables, arithmetic (+=), and standard if/else logic.' },
      { id: 'm1-t3-double-002', topic: 'awk Execution', text: 'Which TWO special blocks allow awk to execute actions outside of the normal line-by-line streaming process?', options: ['START', 'BEGIN', 'END', 'FINISH'], answer: [1, 2], fact: 'BEGIN runs before the file is read (e.g., for headers), and END runs after the file is closed (e.g., for totals).' },
      { id: 'm1-t3-double-003', topic: 'Permissions & Control', text: 'Which TWO commands are used by administrators to modify the security properties of a file rather than its text content?', options: ['chmod', 'sed', 'chown', 'awk'], answer: [0, 2], fact: 'chmod alters access permissions (rwx) and chown alters user/group ownership.' },
      { id: 'm1-t3-double-004', topic: 'awk Intermediate', text: 'Which TWO built-in awk variables are most frequently used to track line numbers and validate column counts?', options: ['NR', 'NF', 'FS', 'OFS'], answer: [0, 1], fact: 'NR tracks the line number, and NF counts the fields on the current line.' },
      { id: 'm1-t3-double-005', topic: 'awk Advanced', text: 'Which TWO awk functions are used to strictly format table outputs and extract specific portions of strings?', options: ['print', 'printf', 'substr', 'match'], answer: [1, 2], fact: 'printf handles alignment/formatting, and substr() handles string extraction.' },
      { id: 'm1-t3-double-006', topic: 'Permissions', text: 'Every file in a Linux filesystem requires which TWO ownership classifications?', options: ['User owner', 'Group owner', 'Domain owner', 'Guest owner'], answer: [0, 1], fact: 'Linux enforces distinct User and Group ownership on every file.' },
      { id: 'm1-t3-double-007', topic: 'Permissions', text: 'Which TWO special permission modes extend the standard rwx model to handle privilege escalation and shared directory restrictions?', options: ['setuid', 'sticky bit', 'read-only', 'hidden'], answer: [0, 1], fact: 'Setuid controls execution privileges, and the sticky bit controls deletion rights.' },
      { id: 'm1-t3-double-008', topic: 'awk Intermediate', text: 'Which TWO operators allow awk to perform inline arithmetic and division without calling external calculators?', options: ['+=', '/', '&&', '=='], answer: [0, 1], fact: '+= handles addition assignment (summing), and / handles division (averaging).' }
    ],
    tf: [
      { id: 'm1-t3-tf-001', topic: 'awk Basics', text: 'Unlike grep which only searches, awk is a complete programming language capable of performing math and splitting data into columns.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; awk was designed to process structured data, generate reports, and act as a standalone programming language.' },
      { id: 'm1-t3-tf-002', topic: 'awk Intermediate', text: 'To calculate a running total in awk using a variable like `sum += $4`, you must explicitly declare `sum = 0` in a BEGIN block first.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; in awk, uninitialized numeric variables automatically start at 0, making inline arithmetic highly efficient.' },
      { id: 'm1-t3-tf-003', topic: 'Permissions', text: 'File permissions (read, write, execute) form the first line of defense in the standard Linux security model.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; access, ownership, and privilege control via the rwx model dictates file security.' },
      { id: 'm1-t3-tf-004', topic: 'Master Pipeline', text: 'In a standard sysadmin pipeline, grep is typically used to filter rows, while awk is used to extract specific columns from those rows.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; the classic pipeline is grep (filter) -> awk (extract/calculate).' },
      { id: 'm1-t3-tf-005', topic: 'awk Basics', text: 'Awk requires you to pipe text into the bc calculator utility in order to perform decimal math.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; awk is a full programming language that performs arithmetic natively.' },
      { id: 'm1-t3-tf-006', topic: 'awk Basics', text: 'In awk, the variable \$0 represents only the very first word on a line.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; \$0 represents the entire line. \$1 represents the first word.' },
      { id: 'm1-t3-tf-007', topic: 'Permissions', text: 'Applying the sticky bit to a directory allows any user to delete any file within it, regardless of ownership.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; the sticky bit PREVENTS users from deleting files they do not own in a shared directory.' },
      { id: 'm1-t3-tf-008', topic: 'Permissions', text: 'The chgrp command is specifically used to change the group ownership of a file, without affecting the user owner.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; while chown can do both, chgrp exclusively targets group ownership.' },
      { id: 'm1-t3-tf-009', topic: 'awk Intermediate', text: 'Awk pattern matching is limited to exact field matches (==) and cannot evaluate regular expressions.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; awk natively supports regex pattern matching (e.g., /pattern/).' },
      { id: 'm1-t3-tf-010', topic: 'awk Advanced', text: 'The printf function in awk uses syntax and format specifiers very similar to the C programming language.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; awk was created by C developers, and printf works identically to its C counterpart.' }
    ],
    identification: [
      { id: 'm1-t3-identification-001', topic: 'awk Basics', text: 'If awk splits a line into words, what variable represents the very first word (or column) on the line?', answer: ['\$1'], fact: '\$1 targets the first field of the current record.' },
      { id: 'm1-t3-identification-002', topic: 'awk Intermediate', text: 'What awk built-in variable keeps track of the total number of lines read so far?', answer: ['NR'], fact: 'NR stands for Number of Records.' },
      { id: 'm1-t3-identification-003', topic: 'awk Intermediate', text: 'What awk built-in variable identifies the total number of columns present on the current line?', answer: ['NF'], fact: 'NF stands for Number of Fields.' },
      { id: 'm1-t3-identification-004', topic: 'awk Advanced', text: 'What C-style awk function formats strings with specific alignments, like %-10s?', answer: ['PRINTF'], fact: 'printf generates aligned, structured output instead of raw text.' },
      { id: 'm1-t3-identification-005', topic: 'awk Advanced', text: 'What string manipulation function extracts a specific portion of a string based on a starting position and length?', answer: ['SUBSTR', 'SUBSTR()'], fact: 'substr() isolates parts of a string inside awk.' },
      { id: 'm1-t3-identification-006', topic: 'awk Basics', text: 'What flag tells awk to change its delimiter from whitespace to a different character?', answer: ['-F', 'F', '-f', 'f'], fact: 'The -F flag sets the Field separator.' },
      { id: 'm1-t3-identification-007', topic: 'Permissions', text: 'Every file has a user owner and a _____ owner, which helps delegate access safely.', answer: ['GROUP'], fact: 'Files possess both user and group ownership classifications.' },
      { id: 'm1-t3-identification-008', topic: 'awk Basics', text: 'If awk splits a line into words, what variable represents the very first word (or column) on the line?', answer: ['\$1'], fact: '\$1 targets the first field of the current record.' },
      { id: 'm1-t3-identification-009', topic: 'awk Intermediate', text: 'What awk built-in variable keeps track of the total number of lines read so far?', answer: ['NR'], fact: 'NR stands for Number of Records.' },
      { id: 'm1-t3-identification-010', topic: 'awk Intermediate', text: 'What awk built-in variable identifies the total number of columns present on the current line?', answer: ['NF'], fact: 'NF stands for Number of Fields.' },
      { id: 'm1-t3-identification-011', topic: 'awk Advanced', text: 'What C-style awk function formats strings with specific alignments, like %-10s?', answer: ['PRINTF'], fact: 'printf generates aligned, structured output instead of raw text.' },
      { id: 'm1-t3-identification-012', topic: 'awk Advanced', text: 'What string manipulation function extracts a specific portion of a string based on a starting position and length?', answer: ['SUBSTR', 'SUBSTR()'], fact: 'substr() isolates parts of a string inside awk.' },
      { id: 'm1-t3-identification-013', topic: 'awk Basics', text: 'What flag tells awk to change its delimiter from whitespace to a different character?', answer: ['-F', 'F', '-f', 'f'], fact: 'The -F flag sets the Field separator.' },
      { id: 'm1-t3-identification-014', topic: 'Permissions', text: 'Every file has a user owner and a _____ owner, which helps delegate access safely.', answer: ['GROUP'], fact: 'Files possess both user and group ownership classifications.' }
    ],
    sequence: [
      { id: 'm1-t3-sequence-001', topic: 'Master Pipeline', text: 'Arrange the pipeline stages to filter for specific staff, clean up delimiters, and conditionally print their salaries.', steps: ['Use grep to isolate lines matching the "Engineering" department.', 'Use sed to convert colon delimiters into spaces.', 'Pipe the space-separated output into awk.', 'Use awk to evaluate if column 4 is > 80000 and print the results.'], answer: [0, 1, 2, 3], fact: 'The pipeline filters noise (grep), sanitizes the format (sed), and performs logical extraction (awk).' },
      { id: 'm1-t3-sequence-002', topic: 'awk Advanced', text: 'Order the execution flow of an awk script designed to calculate and report an average salary.', steps: ['The BEGIN block executes, printing the "SALARY REPORT" header.', 'awk reads line 1, adds \$4 to the sum variable, and increments the count.', 'awk reads the remaining lines, continuously updating the sum and count.', 'The END block executes, printing the sum divided by the count as the average.'], answer: [0, 1, 2, 3], fact: 'awk executes BEGIN blocks first, processes the stream record-by-record, and evaluates END blocks upon completion.' },
      { id: 'm1-t3-sequence-003', topic: 'Master Pipeline', text: 'Arrange the pipeline stages to filter for specific staff, clean up delimiters, and conditionally print their salaries.', steps: ['Use grep to isolate lines matching the "Engineering" department.', 'Use sed to convert colon delimiters into spaces.', 'Pipe the space-separated output into awk.', 'Use awk to evaluate if column 4 is > 80000 and print the results.'], answer: [0, 1, 2, 3], fact: 'The pipeline filters noise (grep), sanitizes the format (sed), and performs logical extraction (awk).' },
      { id: 'm1-t3-sequence-004', topic: 'awk Advanced', text: 'Order the execution flow of an awk script designed to calculate and report an average salary.', steps: ['The BEGIN block executes, printing the "SALARY REPORT" header.', 'awk reads line 1, adds \$4 to the sum variable, and increments the count.', 'awk reads the remaining lines, continuously updating the sum and count.', 'The END block executes, printing the sum divided by the count as the average.'], answer: [0, 1, 2, 3], fact: 'awk executes BEGIN blocks first, processes the stream record-by-record, and evaluates END blocks upon completion.' }
    ]
  }
};