window.quizTopics = window.quizTopics || {};

window.quizTopics.topic7 = {
  id: 'topic7',
  label: 'Topic 7',
  title: 'Dual-OS Part 2',
  description: 'Ubuntu Server, Netplan, SSH, and cross-VM connectivity',
  questions: {
    single: [
      { id: 'm1-t7-single-001', topic: 'Ubuntu', text: 'What tool does Ubuntu Server use for automated and guided installations?', options: ['Anaconda', 'Subiquity', 'Kickstart', 'Preseed'], answer: [1], fact: 'Subiquity is the modern text-based Ubuntu installer.' },
      { id: 'm1-t7-single-002', topic: 'Ubuntu', text: 'What storage partitioning setup is recommended during Ubuntu installation to allow future resizing?', options: ['FAT32', 'LVM (Logical Volume Manager)', 'Raw partitions', 'NTFS'], answer: [1], fact: 'LVM allows flexible volume resizing.' },
      { id: 'm1-t7-single-003', topic: 'Ubuntu', text: 'Which server package must you explicitly select during the Ubuntu installation menu?', options: ['Apache2', 'OpenSSH server', 'Docker Engine', 'Nginx web server'], answer: [1], fact: 'OpenSSH server must be selected during setup.' },
      { id: 'm1-t7-single-004', topic: 'Ubuntu', text: 'What command changes the hostname on Ubuntu permanently?', options: ['hostnamectl set-hostname', 'hostname --change', 'echo name > /etc/hostname', 'sysctl hostname'], answer: [0], fact: 'hostnamectl manages system hostname settings cleanly.' },
      { id: 'm1-t7-single-005', topic: 'Ubuntu', text: 'What service keeps the Ubuntu server clock synchronized with internet time servers?', options: ['ntp-sync', 'chrony / systemd-timesyncd', 'timeserver daemon', 'windows time service'], answer: [1], fact: 'systemd-timesyncd or chrony manages NTP synchronization.' },
      { id: 'm1-t7-single-006', topic: 'Netplan', text: 'What configuration file format does Netplan use?', options: ['XML', 'JSON', 'YAML', 'INI'], answer: [2], fact: 'Netplan uses strict YAML syntax.' },
      { id: 'm1-t7-single-007', topic: 'Netplan', text: 'Which command applies Netplan configuration changes?', options: ['netplan reload', 'netplan apply', 'systemctl restart network', 'netplan commit'], answer: [1], fact: 'netplan apply compiles and applies the configuration.' },
      { id: 'm1-t7-single-008', topic: 'Netplan', text: 'What command applies Netplan settings temporarily with an automatic rollback timeout?', options: ['netplan test', 'netplan try', 'netplan check', 'netplan temporary'], answer: [1], fact: 'netplan try reverts changes if connection is lost.' },
      { id: 'm1-t7-single-009', topic: 'Security', text: 'What firewall utility is standard on Ubuntu Server?', options: ['firewalld', 'UFW (Uncomplicated Firewall)', 'iptables-gui', 'Windows Defender'], answer: [1], fact: 'UFW simplifies iptables management on Ubuntu.' },
      { id: 'm1-t7-single-010', topic: 'Security', text: 'Which configuration file controls SSH daemon parameters like password authentication?', options: ['/etc/ssh/ssh_config', '/etc/ssh/sshd_config', '/etc/ssh/daemon.conf', '/etc/sshd.conf'], answer: [1], fact: 'sshd_config is the server-side configuration file.' },
      { id: 'm1-t7-single-011', topic: 'Security', text: 'What cryptographic key algorithm is recommended for modern SSH key pairs?', options: ['RSA 512', 'DSA 1024', 'ed25519', 'MD5-Key'], answer: [2], fact: 'ed25519 provides strong security and compact keys.' },
      { id: 'm1-t7-single-012', topic: 'Connectivity', text: 'What utility uses SSH to securely transfer files between Windows and Linux?', options: ['ftp', 'scp', 'tftp', 'samba'], answer: [1], fact: 'scp runs over SSH.' },
      { id: 'm1-t7-single-013', topic: 'Connectivity', text: 'Where is the local DNS override hosts file located on Windows systems?', options: ['C:\\Windows\\System32\\drivers\\etc\\hosts', 'C:\\Windows\\hosts.txt', 'C:\\System\\etc\\hosts', 'C:\\Drivers\\hosts'], answer: [0], fact: 'The Windows hosts file is in drivers\\etc\\hosts.' },
      { id: 'm1-t7-single-014', topic: 'Sysadmin Tools', text: 'Which command displays system uptime and load averages on Linux?', options: ['top', 'uptime', 'free', 'df'], answer: [1], fact: 'uptime reports running duration and load metrics.' },
      { id: 'm1-t7-single-015', topic: 'Sysadmin Tools', text: 'What command views system logs in real-time on Ubuntu?', options: ['tail -f /var/log/syslog', 'cat logfile', 'view-syslog', 'journal-watch'], answer: [0], fact: 'tail -f streams log updates live.' }
    ],
    double: [
      { id: 'm1-t7-double-001', topic: 'Ubuntu', text: 'Which TWO post-installation steps are performed on Ubuntu Server?', options: ['Setting the hostname with hostnamectl', 'Configuring timezone with timedatectl', 'Enabling IIS web roles', 'Installing Active Directory DS binaries'], answer: [0, 1], fact: 'Hostname and timezone configuration are standard Ubuntu post-install tasks.' },
      { id: 'm1-t7-double-002', topic: 'Netplan', text: 'Which TWO rules are critical when editing a Netplan YAML file?', options: ['Use spaces instead of tabs for indentation', 'Ensure correct colon spacing', 'Terminate every line with a semicolon', 'Use Windows CRLF line endings exclusively'], answer: [0, 1], fact: 'Netplan YAML requires spaces and proper colon syntax.' },
      { id: 'm1-t7-double-003', topic: 'Security', text: 'Which TWO commands are used to configure UFW firewall on Ubuntu?', options: ['sudo ufw allow ssh', 'sudo ufw enable', 'sudo ufw open port 22', 'sudo ufw start-firewall'], answer: [0, 1], fact: 'ufw allow and ufw enable are standard commands.' },
      { id: 'm1-t7-double-004', topic: 'Security', text: 'Which TWO settings in /etc/ssh/sshd_config harden SSH against attacks?', options: ['PasswordAuthentication no', 'PermitRootLogin no', 'AllowTcpForwarding yes', 'UsePrivilegeSeparation weak'], answer: [0, 1], fact: 'Disabling password authentication and root login improves security.' },
      { id: 'm1-t7-double-005', topic: 'Connectivity', text: 'Which TWO files serve as local static DNS override hosts files across operating systems?', options: ['C:\\Windows\\System32\\drivers\\etc\\hosts', '/etc/hosts', '/etc/dns/records.conf', 'C:\\Windows\\system32\\dns.ini'], answer: [0, 1], fact: 'Windows and Linux both rely on hosts files for local resolution.' },
      { id: 'm1-t7-double-006', topic: 'Sysadmin Tools', text: 'Which TWO commands inspect resource utilization or health on Ubuntu Server?', options: ['free -h', 'df -h', 'sys-check', 'ram-usage'], answer: [0, 1], fact: 'free checks memory and df checks disk space.' },
      { id: 'm1-t7-double-007', topic: 'File Transfer', text: 'Which TWO methods can transfer files between a Windows host and a VirtualBox Ubuntu VM?', options: ['Using scp over SSH', 'Configuring VirtualBox Shared Folders', 'Using Windows Registry Editor', 'Mapping a physical USB floppy drive'], answer: [0, 1], fact: 'SCP and VirtualBox Shared Folders are standard transfer mechanisms.' }
    ],
    tf: [
      { id: 'm1-t7-tf-001', topic: 'Ubuntu', text: 'During Ubuntu Server installation, you must manually press the spacebar to select the OpenSSH server package.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; OpenSSH is an optional installer feature.' },
      { id: 'm1-t7-tf-002', topic: 'Netplan', text: 'Using tab characters instead of spaces in a Netplan YAML file will cause a syntax and application failure.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; YAML strictly prohibits tabs.' },
      { id: 'm1-t7-tf-003', topic: 'Netplan', text: 'The netplan try command automatically reverts network changes if the user loses connection and cannot confirm.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; it protects against permanent lockouts.' },
      { id: 'm1-t7-tf-004', topic: 'Security', text: 'Enabling UFW on Ubuntu without allowing SSH first can lock you out of your remote session.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; UFW denies incoming traffic by default once enabled.' },
      { id: 'm1-t7-tf-005', topic: 'Security', text: 'Disabling password authentication in SSH makes brute-force attacks ineffective against valid user accounts.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; keys are resistant to password guessing.' },
      { id: 'm1-t7-tf-006', topic: 'Connectivity', text: 'Bridged networking is required for two VirtualBox VMs to appear as direct peers on the same physical LAN subnet.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; bridging puts both VMs onto the physical network.' },
      { id: 'm1-t7-tf-007', topic: 'Connectivity', text: 'The scp command requires an active SSH service running on the destination machine.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; SCP transfers files over SSH.' },
      { id: 'm1-t7-tf-008', topic: 'Sysadmin Tools', text: 'The uptime command on Linux shows how long the system has been running and its load average.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; uptime displays run duration and load metrics.' }
    ],
    identification: [
      { id: 'm1-t7-identification-001', topic: 'Ubuntu', text: 'What utility command sets or displays the hostname on modern Ubuntu systems?', answer: ['HOSTNAMECTL'], fact: 'hostnamectl manages hostnames.' },
      { id: 'm1-t7-identification-002', topic: 'Netplan', text: 'Name the YAML-based network configuration utility used in modern Ubuntu Server releases.', answer: ['NETPLAN'], fact: 'Netplan manages network interfaces via YAML.' },
      { id: 'm1-t7-identification-003', topic: 'Netplan', text: 'What Netplan command applies configuration changes with an automatic rollback timeout safeguard?', answer: ['NETPLAN TRY'], fact: 'netplan try prevents remote lockouts.' },
      { id: 'm1-t7-identification-004', topic: 'Security', text: 'What acronym stands for Ubuntu\'s default uncomplicated firewall utility?', answer: ['UFW'], fact: 'UFW manages firewall rules easily.' },
      { id: 'm1-t7-identification-005', topic: 'Security', text: 'Name the configuration file path used to adjust SSH daemon settings like password login.', answer: ['/ETC/SSH/SSHD_CONFIG'], fact: 'sshd_config controls server SSH rules.' },
      { id: 'm1-t7-identification-006', topic: 'Connectivity', text: 'What command-line protocol tool securely copies files over SSH?', answer: ['SCP'], fact: 'scp performs secure file copies.' },
      { id: 'm1-t7-identification-007', topic: 'Sysadmin Tools', text: 'What Linux command reports disk space usage in human-readable format?', answer: ['DF -H'], fact: 'df -h summarizes filesystem disk space.' },
      { id: 'm1-t7-identification-008', topic: 'Sysadmin Tools', text: 'What Linux command reports memory and swap utilization?', answer: ['FREE -H'], fact: 'free -h displays RAM and swap usage.' },
      { id: 'm1-t7-identification-009', topic: 'Ubuntu', text: 'The Ubuntu Server installer used in this topic is _____.', answer: ['SUBIQUITY'], fact: 'Subiquity is Ubuntu Server\'s modern text-based installer.' },
      { id: 'm1-t7-identification-010', topic: 'Ubuntu', text: '_____ lets Ubuntu disk volumes be resized more flexibly after installation.', answer: ['LVM', 'LOGICAL VOLUME MANAGER'], fact: 'LVM supports flexible logical volume management and resizing.' },
      { id: 'm1-t7-identification-011', topic: 'Ubuntu', text: 'During installation, select _____ to permit remote SSH administration.', answer: ['OPENSSH SERVER', 'OPENSSH'], fact: 'The OpenSSH server package enables incoming SSH connections.' },
      { id: 'm1-t7-identification-012', topic: 'Ubuntu', text: 'Complete the update command: sudo apt update && sudo apt _____ -y.', answer: ['upgrade'], fact: 'The command refreshes package metadata and installs available upgrades.' },
      { id: 'm1-t7-identification-013', topic: 'Ubuntu', text: 'Set an Ubuntu hostname with hostnamectl set-_____.', answer: ['hostname'], fact: 'hostnamectl set-hostname changes the persistent hostname.' },
      { id: 'm1-t7-identification-014', topic: 'Ubuntu', text: 'Use _____ to set the timezone to Asia/Manila.', answer: ['timedatectl set-timezone Asia/Manila', 'TIMEDATECTL SET-TIMEZONE ASIA/MANILA'], fact: 'timedatectl set-timezone configures the system timezone.' },
      { id: 'm1-t7-identification-015', topic: 'Ubuntu', text: 'Enable network time synchronization with timedatectl set-ntp _____.', answer: ['true'], fact: 'timedatectl set-ntp true enables the built-in NTP client.' },
      { id: 'm1-t7-identification-016', topic: 'Netplan', text: 'Netplan configuration files are stored in _____.', answer: ['/etc/netplan/', '/etc/netplan', 'ETC/NETPLAN'], fact: 'Ubuntu stores Netplan YAML files in /etc/netplan/.' },
      { id: 'm1-t7-identification-017', topic: 'Netplan', text: 'Use ip _____ to identify a Linux network interface before configuring Netplan.', answer: ['a', 'ADDRESS'], fact: 'ip a displays interfaces and their addresses.' },
      { id: 'm1-t7-identification-018', topic: 'Netplan', text: 'In Netplan YAML, _____ disables DHCP for an interface.', answer: ['dhcp4: false', 'DHCP4 FALSE'], fact: 'dhcp4: false disables DHCPv4 for that interface.' },
      { id: 'm1-t7-identification-019', topic: 'Netplan', text: 'Apply a completed Netplan configuration with sudo netplan _____.', answer: ['apply'], fact: 'netplan apply reads and activates the YAML configuration.' },
      { id: 'm1-t7-identification-020', topic: 'Security', text: 'Allow SSH through the Ubuntu firewall with sudo ufw allow _____.', answer: ['ssh'], fact: 'ufw allow ssh permits inbound SSH traffic before enabling the firewall.' },
      { id: 'm1-t7-identification-021', topic: 'Security', text: '_____ disables password-based SSH logins in sshd_config.', answer: ['PasswordAuthentication no', 'PASSWORDAUTHENTICATION NO'], fact: 'PasswordAuthentication no disables SSH password login.' },
      { id: 'm1-t7-identification-022', topic: 'Security', text: 'Generate a modern SSH key pair with ssh-keygen -t _____.', answer: ['ed25519'], fact: 'ssh-keygen -t ed25519 creates an Ed25519 SSH key pair.' },
      { id: 'm1-t7-identification-023', topic: 'Connectivity', text: 'The Windows hosts file used for local name resolution is _____.', answer: ['C:\\Windows\\System32\\drivers\\etc\\hosts', 'C:/WINDOWS/SYSTEM32/DRIVERS/ETC/HOSTS'], fact: 'The Windows hosts file provides local static hostname overrides.' },
      { id: 'm1-t7-identification-024', topic: 'Connectivity', text: 'Linux stores local static hostname mappings in _____.', answer: ['/etc/hosts', 'ETC/HOSTS'], fact: '/etc/hosts provides local static hostname mappings on Linux.' },
      { id: 'm1-t7-identification-025', topic: 'Connectivity', text: 'Install the Windows OpenSSH Server capability with _____.', answer: ['Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0', 'ADD-WINDOWSCAPABILITY -ONLINE -NAME OPENSSH.SERVER~~~~0.0.1.0'], fact: 'Add-WindowsCapability installs the Windows OpenSSH Server feature.' },
      { id: 'm1-t7-identification-026', topic: 'Connectivity', text: 'Start the Windows SSH server with Start-Service _____.', answer: ['sshd'], fact: 'Start-Service sshd starts the Windows OpenSSH server.' },
      { id: 'm1-t7-identification-027', topic: 'File Transfer', text: 'Copy an entire directory through SCP using the option _____.', answer: ['-r', 'SCP -R'], fact: 'The -r option makes SCP copy directories recursively.' },
      { id: 'm1-t7-identification-028', topic: 'File Transfer', text: 'Mount a VirtualBox shared folder on Ubuntu with the filesystem type _____.', answer: ['vboxsf', 'VBOXSF'], fact: 'vboxsf is the filesystem type used by VirtualBox shared folders.' }
    ],
    sequence: [
      { id: 'm1-t7-sequence-001', topic: 'Netplan', text: 'Order the steps required to configure and apply a static IP address on Ubuntu Server using Netplan.', steps: ['Use the ip a command to identify the network interface name.', 'Edit the Netplan YAML configuration file with proper indentation.', 'Run sudo netplan apply to enforce the network settings.', 'Run ip a show to verify the static IP assignment.'], answer: [0, 1, 2, 3], fact: 'Netplan configuration requires interface identification, YAML editing, apply, and verification.' },
      { id: 'm1-t7-sequence-002', topic: 'Security', text: 'Arrange the steps to establish secure, key-based SSH authentication from a host to an Ubuntu VM.', steps: ['Run ssh-keygen -t ed25519 on the host machine.', 'Run ssh-copy-id user@IP to send the public key to the server.', 'Edit /etc/ssh/sshd_config to set PasswordAuthentication no.', 'Restart or reload the SSH service on the Ubuntu server.'], answer: [0, 1, 2, 3], fact: 'Key-based auth requires key generation, key transfer, hardening, and a service restart.' },
      { id: 'm1-t7-sequence-003', topic: 'Ubuntu', text: 'Arrange the standard post-installation verification and update steps for a fresh Ubuntu Server.', steps: ['Run sudo apt update to refresh the package repository lists.', 'Run sudo apt upgrade -y to install available software patches.', 'Use timedatectl to set the correct local timezone.', 'Use uptime, free -h, and df -h to verify system health.'], answer: [0, 1, 2, 3], fact: 'The post-install checklist covers updates, timezone, and resource health checks.' }
    ]
  }
};
