window.quizTopics = window.quizTopics || {};

window.quizTopics.topic6 = {
  id: 'topic6',
  label: 'Topic 6',
  title: 'Dual-OS Part 1',
  description: 'WSL 2, VirtualBox, and Windows Server 2022',
  questions: {
    single: [
      { id: 'm1-t6-single-001', topic: 'WSL 2', text: 'What core feature distinguishes WSL 2 from WSL 1?', options: ['System call translation', 'A real Linux kernel in a utility VM', 'Direct Windows NT API calls', 'Complete absence of a filesystem'], answer: [1], fact: 'WSL 2 runs a genuine Linux kernel inside a lightweight utility VM.' },
      { id: 'm1-t6-single-002', topic: 'WSL 2', text: 'Which command is used to manually update the WSL 2 custom Linux kernel?', options: ['wsl --update', 'apt update kernel', 'wsl --patch', 'dism /update-wsl'], answer: [0], fact: 'wsl --update updates the Microsoft-built WSL 2 kernel.' },
      { id: 'm1-t6-single-003', topic: 'WSL 2', text: 'Before installing a Linux distribution, which Windows feature must be enabled alongside WSL?', options: ['Hyper-V Replica', 'Virtual Machine Platform', 'IIS Management Console', 'Active Directory Lightweight Directory Services'], answer: [1], fact: 'Virtual Machine Platform and WSL features are prerequisites.' },
      { id: 'm1-t6-single-004', topic: 'WSL 2', text: 'Which flag is used with the wsl command to list online available distributions?', options: ['--show-all', '--list --online', '-l -v', '--available'], answer: [1], fact: 'wsl --list --online displays valid installable distributions.' },
      { id: 'm1-t6-single-005', topic: 'WSL 2', text: 'What command terminates all running WSL instances immediately to free RAM?', options: ['wsl --kill-all', 'wsl --stop', 'wsl --shutdown', 'wsl --clear'], answer: [2], fact: 'wsl --shutdown terminates all active instances.' },
      { id: 'm1-t6-single-006', topic: 'WSL 2', text: 'How do you back up an entire WSL 2 distribution to a tarball file?', options: ['wsl --export', 'wsl --backup', 'wsl --tar', 'wsl --save'], answer: [0], fact: 'wsl --export creates a tarball backup of the distribution filesystem.' },
      { id: 'm1-t6-single-007', topic: 'WSL 2', text: 'What command removes a registered WSL distribution instance completely?', options: ['wsl --remove', 'wsl --unregister', 'wsl --delete', 'wsl --purge'], answer: [1], fact: 'wsl --unregister uninstalls the specified distribution.' },
      { id: 'm1-t6-single-008', topic: 'WSL 2', text: 'Where must the .wslconfig file be placed to set resource limits like memory caps?', options: ['C:\\Windows\\System32', 'C:\\Users\\YourName\\.wslconfig', '/etc/wsl.conf', 'C:\\Program Files\\WSL'], answer: [1], fact: '.wslconfig resides in the Windows user profile directory.' },
      { id: 'm1-t6-single-009', topic: 'WSL 2', text: 'Under what directory path is the Windows C: drive automatically mounted inside WSL 2?', options: ['/c', '/mnt/c', '/windows/c', '/media/c'], answer: [1], fact: 'WSL 2 automatically mounts Windows drives under /mnt/.' },
      { id: 'm1-t6-single-010', topic: 'WSL 2', text: 'What command launches VS Code directly from the current WSL directory?', options: ['code .', 'vscode-server', 'code-wsl .', 'open-vs .'], answer: [0], fact: 'The code . command invokes the VS Code server for WSL.' },
      { id: 'm1-t6-single-011', topic: 'WSL 2', text: 'Which feature allows running Linux GUI apps seamlessly on a Windows desktop without a third-party X server?', options: ['Xming', 'WSLg', 'Cygwin', 'WinX11'], answer: [1], fact: 'WSLg provides built-in X11 and Wayland support.' },
      { id: 'm1-t6-single-012', topic: 'VirtualBox', text: 'What is the minimum recommended RAM size for a Windows Server 2022 VirtualBox VM in our labs?', options: ['1024 MB', '2048 MB', '4096 MB', '8192 MB'], answer: [2], fact: 'Windows Server 2022 requires at least 4GB of RAM.' },
      { id: 'm1-t6-single-013', topic: 'VirtualBox', text: 'What virtual disk file type is standard for VirtualBox?', options: ['VHD', 'VDI', 'VMDK', 'QCOW2'], answer: [1], fact: 'VDI stands for VirtualBox Disk Image.' },
      { id: 'm1-t6-single-014', topic: 'VirtualBox', text: 'Why should you install VirtualBox Guest Additions on a VM?', options: ['To enable clipboard sharing and dynamic screen resizing', 'To increase the physical CPU clock speed', 'To bypass Windows activation', 'To convert the VM into a Type-1 hypervisor'], answer: [0], fact: 'Guest Additions provide drivers for integration features.' },
      { id: 'm1-t6-single-015', topic: 'VirtualBox', text: 'Which VirtualBox menu option lets you save a point-in-time state of your VM?', options: ['Machine -> Take Snapshot', 'File -> Export Appliance', 'Devices -> Insert State', 'Help -> Backup'], answer: [0], fact: 'Snapshots are managed via the Machine menu.' },
      { id: 'm1-t6-single-016', topic: 'VirtualBox', text: 'Which VirtualBox networking mode hides the VM behind the host using translation, preventing direct inbound host access?', options: ['Bridged Adapter', 'Internal Network', 'NAT', 'Host-Only'], answer: [2], fact: 'NAT maps outbound traffic but hides the VM from inbound access.' },
      { id: 'm1-t6-single-017', topic: 'VirtualBox', text: 'Which networking mode creates a private LAN strictly between VMs with no internet or host connection?', options: ['NAT', 'Internal Network', 'Bridged Adapter', 'Generic Driver'], answer: [1], fact: 'Internal Network isolates communication strictly between participating VMs.' },
      { id: 'm1-t6-single-018', topic: 'VirtualBox', text: 'Which networking mode makes a VM act like a physical machine directly on your physical router LAN?', options: ['NAT', 'Bridged Adapter', 'Internal Network', 'NAT Network'], answer: [1], fact: 'Bridged Adapter bridges the virtual NIC to the physical network card.' },
      { id: 'm1-t6-single-019', topic: 'Windows Server', text: 'Which Windows Server 2022 installation option includes the standard graphical user interface?', options: ['Server Core', 'Desktop Experience', 'Nano Server', 'CLI Mode'], answer: [1], fact: 'Desktop Experience provides the full graphical shell.' },
      { id: 'm1-t6-single-020', topic: 'Windows Server', text: 'What is the name of the legacy text-based menu utility used for quick configuration on Windows Server?', options: ['netsh', 'sconfig', 'winmsd', 'sysdm.cpl'], answer: [1], fact: 'sconfig provides a text menu for hostname, IP, and updates.' },
      { id: 'm1-t6-single-021', topic: 'Windows Server', text: 'What PowerShell cmdlet is used to rename a computer?', options: ['Set-ComputerName', 'Rename-Computer', 'Update-HostName', 'Change-Name'], answer: [1], fact: 'Rename-Computer alters the host name.' },
      { id: 'm1-t6-single-022', topic: 'Windows Server', text: 'Which PowerShell cmdlet assigns a static IPv4 address to an interface?', options: ['New-NetIPAddress', 'Set-IPAddress', 'Add-IPv4Config', 'netsh interface ip'], answer: [0], fact: 'New-NetIPAddress configures static IP settings.' },
      { id: 'm1-t6-single-023', topic: 'Windows Server', text: 'Why must you set the correct timezone, such as Asia/Manila, on a Windows Server?', options: ['To prevent Kerberos authentication failures due to time skew', 'To speed up file copying across SMB', 'To enable Remote Desktop connections', 'To activate Windows Server licenses'], answer: [0], fact: 'Kerberos tickets have a strict time tolerance.' },
      { id: 'm1-t6-single-024', topic: 'Windows Server', text: 'What command opens the Network Connections control panel GUI directly?', options: ['sysdm.cpl', 'ncpa.cpl', 'appwiz.cpl', 'compmgmt.msc'], answer: [1], fact: 'ncpa.cpl opens Network Connections.' },
      { id: 'm1-t6-single-025', topic: 'Windows Server', text: 'What feature group must be installed to manage Active Directory and DNS via graphical tools on Windows?', options: ['RSAT', 'WDS', 'IIS', 'WMI'], answer: [0], fact: 'RSAT provides Remote Server Administration Tools.' }
    ],
    double: [
      { id: 'm1-t6-double-001', topic: 'WSL 2', text: 'Which TWO features are characteristic of WSL 2 architecture?', options: ['Runs a real Linux kernel', 'Uses a lightweight utility VM', 'Requires a full Type-1 hypervisor installation', 'Translates POSIX syscalls to Windows NT APIs directly'], answer: [0, 1], fact: 'WSL 2 runs a real Linux kernel in a utility VM.' },
      { id: 'm1-t6-double-002', topic: 'WSL 2', text: 'Which TWO commands are used in WSL management?', options: ['wsl -l -v', 'wsl --shutdown', 'wsl --format', 'wsl --reboot-host'], answer: [0, 1], fact: 'wsl -l -v lists versions and wsl --shutdown stops instances.' },
      { id: 'm1-t6-double-003', topic: 'WSL 2', text: 'Which TWO steps are involved in backing up and restoring WSL distributions?', options: ['wsl --export', 'wsl --import', 'wsl --clone', 'wsl --snapshot-save'], answer: [0, 1], fact: 'Export and import manage tarball backups.' },
      { id: 'm1-t6-double-004', topic: 'VirtualBox', text: 'Which TWO network adapter modes allow a VirtualBox guest to communicate with external networks or hosts?', options: ['Bridged Adapter', 'NAT', 'Internal Network', 'Null Driver'], answer: [0, 1], fact: 'Bridged and NAT both provide external network connectivity.' },
      { id: 'm1-t6-double-005', topic: 'VirtualBox', text: 'Which TWO options are configured when creating a virtual hard disk in VirtualBox?', options: ['Dynamically allocated or Fixed size', 'VDI file type', 'NTFS formatting', 'EXT4 journaling'], answer: [0, 1], fact: 'VirtualBox prompts for storage allocation type and disk image format.' },
      { id: 'm1-t6-double-006', topic: 'Windows Server', text: 'Which TWO PowerShell cmdlets are used for post-configuring Windows Server network and time settings?', options: ['New-NetIPAddress', 'Set-TimeZone', 'Set-LinuxClock', 'Update-NetAdapter'], answer: [0, 1], fact: 'New-NetIPAddress sets IPs and Set-TimeZone sets timezones.' },
      { id: 'm1-t6-double-007', topic: 'Windows Server', text: 'Which TWO options represent valid Windows Server 2022 installation editions?', options: ['Standard (Desktop Experience)', 'Datacenter', 'Enterprise Core Pro', 'Ultimate Server Edition'], answer: [0, 1], fact: 'Standard and Datacenter are standard editions.' },
      { id: 'm1-t6-double-008', topic: 'Windows Server', text: 'Which TWO commands or tools open Windows configuration utilities via GUI shortcuts?', options: ['ncpa.cpl', 'sysdm.cpl', 'netconfig.exe', 'server-gui.msc'], answer: [0, 1], fact: 'ncpa.cpl opens network connections and sysdm.cpl opens system properties.' }
    ],
    tf: [
      { id: 'm1-t6-tf-001', topic: 'WSL 2', text: 'WSL 2 runs a real Linux kernel inside a lightweight utility VM.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; WSL 2 uses a genuine Linux kernel architecture.' },
      { id: 'm1-t6-tf-002', topic: 'WSL 2', text: 'WSL 1 offers better system call compatibility than WSL 2 because it uses a real kernel.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; WSL 2 has broad syscall compatibility because of its real kernel.' },
      { id: 'm1-t6-tf-003', topic: 'WSL 2', text: 'You can limit WSL 2 memory consumption by creating a .wslconfig file in your Windows user profile.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; .wslconfig allows resource caps.' },
      { id: 'm1-t6-tf-004', topic: 'VirtualBox', text: 'A NAT network adapter allows the host machine to directly RDP into a VirtualBox VM without port forwarding.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; NAT blocks direct inbound connections from the host.' },
      { id: 'm1-t6-tf-005', topic: 'VirtualBox', text: 'VirtualBox Snapshots allow you to save a VM state and revert back if an installation fails.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; snapshots provide instant rollback states.' },
      { id: 'm1-t6-tf-006', topic: 'Windows Server', text: 'Windows Server 2022 requires static IP configuration because servers must not rely on dynamic DHCP changes.', options: ['TRUE', 'FALSE'], answer: [0], fact: 'True; server roles require stable static IPs.' },
      { id: 'm1-t6-tf-007', topic: 'Windows Server', text: 'Kerberos authentication in Active Directory will succeed even if client and server clocks differ by several hours.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; Kerberos has a strict time skew tolerance.' },
      { id: 'm1-t6-tf-008', topic: 'Windows Server', text: 'Server Core installations of Windows Server 2022 include a full graphical Start Menu.', options: ['TRUE', 'FALSE'], answer: [1], fact: 'False; Server Core is CLI and PowerShell only.' }
    ],
    identification: [
      { id: 'm1-t6-identification-001', topic: 'WSL 2', text: 'What command-line tool checks installed WSL distributions and their active versions?', answer: ['WSL -L -V', 'WSL --LIST --VERBOSE'], fact: 'wsl -l -v lists installed distributions and versions.' },
      { id: 'm1-t6-identification-002', topic: 'WSL 2', text: 'What filename must be created in the Windows user profile folder to configure WSL resource limits?', answer: ['.WSLCONFIG'], fact: '.wslconfig sets global WSL settings.' },
      { id: 'm1-t6-identification-003', topic: 'WSL 2', text: 'What absolute path mounts the Windows C: drive inside WSL 2?', answer: ['/MNT/C'], fact: '/mnt/c maps the Windows C: drive.' },
      { id: 'm1-t6-identification-004', topic: 'VirtualBox', text: 'Name the VirtualBox network mode that bridges guest virtual adapters directly to the physical network card.', answer: ['BRIDGED ADAPTER', 'BRIDGED MODE', 'BRIDGED'], fact: 'Bridged Adapter places VMs directly on the physical LAN.' },
      { id: 'm1-t6-identification-005', topic: 'VirtualBox', text: 'What VirtualBox feature saves a point-in-time machine state for easy recovery?', answer: ['SNAPSHOT', 'SNAPSHOTS'], fact: 'Snapshots record disk and memory states.' },
      { id: 'm1-t6-identification-006', topic: 'Windows Server', text: 'What PowerShell cmdlet is used to rename a Windows computer?', answer: ['RENAME-COMPUTER'], fact: 'Rename-Computer changes computer names.' },
      { id: 'm1-t6-identification-007', topic: 'Windows Server', text: 'Name the text-based configuration menu utility available in Windows Server for quick setup.', answer: ['SCONFIG'], fact: 'sconfig provides quick server setup options.' },
      { id: 'm1-t6-identification-008', topic: 'Windows Server', text: 'What tool acronym represents Remote Server Administration Tools for managing roles like AD and DNS?', answer: ['RSAT'], fact: 'RSAT supplies GUI administrative tools.' }
    ],
    sequence: [
      { id: 'm1-t6-sequence-001', topic: 'WSL 2', text: 'Arrange the steps to properly back up and restore a WSL 2 distribution.', steps: ['Run wsl --export to create a .tar backup file.', 'Run wsl --unregister to remove the original instance.', 'Run wsl --import to restore the backup to the new path.', 'Run wsl -l -v to verify the new instance is running.'], answer: [0, 1, 2, 3], fact: 'WSL backup workflow uses export, unregister, and import.' },
      { id: 'm1-t6-sequence-002', topic: 'Windows Server', text: 'Order the PowerShell steps required to configure a static network identity for Windows Server 2022.', steps: ['Open Windows PowerShell as an Administrator.', 'Use New-NetIPAddress to assign the static IP and gateway.', 'Use Set-DnsClientServerAddress to define the DNS server.', 'Run ipconfig /all to visually verify the network settings.'], answer: [0, 1, 2, 3], fact: 'Windows static IP setup requires admin shell, IP assignment, DNS configuration, and verification.' }
    ]
  }
};
